language: generic
dist: trusty
sudo: true

#Build order
#    before_install
#    install
#    before_script
#    script
#    after_success / after_failure
#    after_script
#
#After the the after_script has run.
#
#    before_deploy
#    deploy
#    after_deploy


notifications:
  email:
    recipients:
      - coders@taqtiqa.com
    on_success: [always]
    on_failure: [always]

env:
  global:
    - secure: RRzSkAp27+Jr1NRHvdfJ51TNzz4YecpJ4nOMrspb9gEphzQbbyQq9rzKvteB7hkwupbwuu7TvYltQemGnPBc8kaFPSobMxyvpGRnwU1ot6OhTRlct/r/v6V05YZg/rpMELzaUcBtGyuc7W5dnpP5PLZJ+cjT1dnkYd8ZsPNvX57w6TWz6lswG+Ezhj5HJ83dbk2+6DUYzsiCYys2rCEv5fFsLYfCX2DlZ1H5sskYFCGRc/hZO2b91cEc6A9aIABp3QGk24r5Wk6nbcnA7AbK3EiwjaKZNLsT192DohVp//Y7b2QHoitjv5d61KcRFyWsCgd2lWjXNkCN8tUPRKmqj0g85jG8kWI2whPHyRzfhEXp71sd+DLGLPc7Lrgy6zDF+OFREjw1UeolvhDL3tnxhAK2K4bq3MmPKms/Su2yEZIm3aN7SmqaMAsVbV1rciRWiJ6AooBnaOWRD8Axkl91xvqA7sZxUXrQTjQfaJ0j2fjHw/BNqZ66i0KeOfd7dsbJY96I1PoMYVNdpPzqruFFplJBYbfnAKQTPFAnuFPJphzH91gt3D7n/A8ryplb1FpCGHWcA3LXK7j3x2GAjXLJeD3Vn7eopbbqMMA1QQwxYu0qNlTuWh25lK+LnBnUMINeHt7pRsa6eg4Jki0cLIFT510qhv91Kt+m/02+7MRZRLY=
  matrix:
    - ARCH=amd64

before_install:
  - git clone https://github.com/taqtiqa/ci.git
  - cat ci/travis/install-acbuild.sh | sudo bash >> >(tee -a before_install-stdout.log) 2> >(tee -a before_install-stderr.log >&2)
  - cat ./scripts/openssl.sh | sudo bash >/dev/null 2> >(tee -a before_install-stderr.log >&2)

before_script:
  - openssl aes-256-cbc -pass env:ACI_SECRET -in ./rkt-base-privatekeys.gpg.enc -out ./rkt-base-privatekeys.gpg -d -a

script:
  - cat ./rkt-base.sh | sudo bash >> >(tee -a script-stdout.log) 2> >(tee -a script-stderr.log >&2)

after_script: # here's a build step block
  - echo "We can put normal shell commands here"
  - echo "more shell commands here"
  - cat ./scripts/deploy.sh | bash


before_deploy:
  - echo 'ready?'

deploy:
  - provider: releases
    api_key:
      secure: "HZkNH2RUBvhOp0Xq4vLHnDMFdcnkI5s9KnJGl32eD5YoGV73EZK5JD28eQFkcsDGbfUoPaYnnwgjh8wzOHaysYl8OfVMpum1x2XglEjGsrgiQ/cXJwtJs3+e+n7qv4XPiArSiMcrCupgheHVwdd6WygSZGTLCjIpfWdth5l7tenFKZImtummUrm/X6B+7Fqlr/l1o+zOEjcwJ4NGQDwUQIGDJmxH76tt1ufKuNAsY2U+k1oUfD8PyyiS8ERGEne0BaFTt0kzfIXjUUcZEnV9p1c5mRvabFfwU+gTKLn4tnYwaU2Lsmu/9t3w0neOEOZ+vI0ANYbz2Ingm5vHzwN5aaHxRHthz9LkjYo8R9HLIiOZni4+qy0mWKNpvkI7Aj5yIF1PlR3iMJVXeOWUDorgJ0CYHuWA048Fnf511/UOhC5G3TygPi63QOD1aMU8cjpdQND1SfDXfoJSSCmN6D+FlvbZadlcAMIaFs+6Sr672omcBdg8fTQHOUM/AiVY383LwtDq/9j6W9OHBKdVp9Fxy/fRJ+9haZjTekBEHujakG8xes6EkTteQOWa06Wua+I31U6ym8uh1uiHSBqBoi1IRLP9U56+q6x6UTKWUHkpW7VJvh+U0m6folpQ2zMia2uRebi0uwG7jdZVJUy5qtfPVxPSECmiE70VPHnW5Xz/P08="
    file:
      - "${ACI_NAME}-${TRAVIS_TAG}-linux-${ARCH}.aci"
      - "${ACI_NAME}-${TRAVIS_TAG}-linux-${ARCH}.aci.asc"
    skip_cleanup: true
    on:
      repo: $TRAVIS_REPO_SLUG
      tags: true
      all_branches: true

after_deploy:
  - echo "We can put normal shell commands here"
